/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanHistoryRouteImport } from './routes/scan-history'
import { Route as ReportRouteImport } from './routes/report'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as CaptchaRouteImport } from './routes/captcha'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultWarningRouteImport } from './routes/result/warning'
import { Route as ResultSafeRouteImport } from './routes/result/safe'
import { Route as ResultCriticalRouteImport } from './routes/result/critical'

const ScanHistoryRoute = ScanHistoryRouteImport.update({
  id: '/scan-history',
  path: '/scan-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptchaRoute = CaptchaRouteImport.update({
  id: '/captcha',
  path: '/captcha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultWarningRoute = ResultWarningRouteImport.update({
  id: '/result/warning',
  path: '/result/warning',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultSafeRoute = ResultSafeRouteImport.update({
  id: '/result/safe',
  path: '/result/safe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultCriticalRoute = ResultCriticalRouteImport.update({
  id: '/result/critical',
  path: '/result/critical',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/captcha': typeof CaptchaRoute
  '/loading': typeof LoadingRoute
  '/report': typeof ReportRoute
  '/scan-history': typeof ScanHistoryRoute
  '/result/critical': typeof ResultCriticalRoute
  '/result/safe': typeof ResultSafeRoute
  '/result/warning': typeof ResultWarningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/captcha': typeof CaptchaRoute
  '/loading': typeof LoadingRoute
  '/report': typeof ReportRoute
  '/scan-history': typeof ScanHistoryRoute
  '/result/critical': typeof ResultCriticalRoute
  '/result/safe': typeof ResultSafeRoute
  '/result/warning': typeof ResultWarningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/captcha': typeof CaptchaRoute
  '/loading': typeof LoadingRoute
  '/report': typeof ReportRoute
  '/scan-history': typeof ScanHistoryRoute
  '/result/critical': typeof ResultCriticalRoute
  '/result/safe': typeof ResultSafeRoute
  '/result/warning': typeof ResultWarningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/captcha'
    | '/loading'
    | '/report'
    | '/scan-history'
    | '/result/critical'
    | '/result/safe'
    | '/result/warning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/captcha'
    | '/loading'
    | '/report'
    | '/scan-history'
    | '/result/critical'
    | '/result/safe'
    | '/result/warning'
  id:
    | '__root__'
    | '/'
    | '/captcha'
    | '/loading'
    | '/report'
    | '/scan-history'
    | '/result/critical'
    | '/result/safe'
    | '/result/warning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptchaRoute: typeof CaptchaRoute
  LoadingRoute: typeof LoadingRoute
  ReportRoute: typeof ReportRoute
  ScanHistoryRoute: typeof ScanHistoryRoute
  ResultCriticalRoute: typeof ResultCriticalRoute
  ResultSafeRoute: typeof ResultSafeRoute
  ResultWarningRoute: typeof ResultWarningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan-history': {
      id: '/scan-history'
      path: '/scan-history'
      fullPath: '/scan-history'
      preLoaderRoute: typeof ScanHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captcha': {
      id: '/captcha'
      path: '/captcha'
      fullPath: '/captcha'
      preLoaderRoute: typeof CaptchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/warning': {
      id: '/result/warning'
      path: '/result/warning'
      fullPath: '/result/warning'
      preLoaderRoute: typeof ResultWarningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/safe': {
      id: '/result/safe'
      path: '/result/safe'
      fullPath: '/result/safe'
      preLoaderRoute: typeof ResultSafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/critical': {
      id: '/result/critical'
      path: '/result/critical'
      fullPath: '/result/critical'
      preLoaderRoute: typeof ResultCriticalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptchaRoute: CaptchaRoute,
  LoadingRoute: LoadingRoute,
  ReportRoute: ReportRoute,
  ScanHistoryRoute: ScanHistoryRoute,
  ResultCriticalRoute: ResultCriticalRoute,
  ResultSafeRoute: ResultSafeRoute,
  ResultWarningRoute: ResultWarningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
